#!/usr/bin/env node
/**
 * Seeds the school directory from the U.S. Dept. of Education College Scorecard API
 * (https://collegescorecard.ed.gov/data/api-documentation/).
 *
 * Fetches the 500 largest predominantly-bachelor's-degree US institutions and writes:
 *   - supabase/seed/schools.json                (raw dataset, checked in)
 *   - supabase/migrations/0002_seed_schools.sql (INSERTs to paste into Supabase)
 *
 * Usage:  SCORECARD_API_KEY=your-key node scripts/seed-schools.mjs
 * DEMO_KEY works for a one-off pull (rate-limited). Get a free key at https://api.data.gov/signup/
 */
import { writeFileSync, mkdirSync } from "node:fs";

const API_KEY = process.env.SCORECARD_API_KEY || "DEMO_KEY";
const FIELDS = [
  "id",
  "school.name",
  "school.city",
  "school.state",
  "school.ownership",
  "school.school_url",
  "latest.admissions.admission_rate.overall",
  "latest.student.size",
].join(",");

const OWNERSHIP = { 1: "Public", 2: "Private nonprofit", 3: "Private for-profit" };

function domainFromUrl(url) {
  if (!url) return null;
  try {
    const u = new URL(url.startsWith("http") ? url : `https://${url}`);
    return u.hostname.replace(/^www\./, "");
  } catch {
    return null;
  }
}

const schools = [];
for (let page = 0; page < 5; page++) {
  const url =
    `https://api.data.gov/ed/collegescorecard/v1/schools?api_key=${API_KEY}` +
    `&fields=${FIELDS}&school.degrees_awarded.predominant=3&school.operating=1` +
    `&sort=latest.student.size:desc&per_page=100&page=${page}`;
  process.stdout.write(`Fetching page ${page + 1}/5… `);
  const res = await fetch(url);
  if (!res.ok) {
    console.error(`\nAPI error ${res.status}: ${await res.text()}`);
    process.exit(1);
  }
  const json = await res.json();
  for (const r of json.results) {
    schools.push({
      scorecard_id: String(r["id"]),
      name: r["school.name"],
      city: r["school.city"],
      state: r["school.state"],
      ownership: OWNERSHIP[r["school.ownership"]] ?? null,
      admission_rate: r["latest.admissions.admission_rate.overall"],
      enrollment: r["latest.student.size"],
      domain: domainFromUrl(r["school.school_url"]),
      url: r["school.school_url"],
    });
  }
  console.log(`ok (${json.results.length})`);
}

mkdirSync("supabase/seed", { recursive: true });
writeFileSync("supabase/seed/schools.json", JSON.stringify(schools, null, 2));

const esc = (s) => (s == null ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const num = (n) => (n == null ? "null" : n);
const rows = schools.map(
  (s) =>
    `(${esc(s.scorecard_id)}, ${esc(s.name)}, ${esc(s.city)}, ${esc(s.state)}, ${esc(s.ownership)}, ${num(s.admission_rate)}, ${num(s.enrollment)}, ${esc(s.domain)}, ${esc(s.url)})`
);
const sql = `-- Auto-generated by scripts/seed-schools.mjs from the College Scorecard API.
-- ${schools.length} largest predominantly-bachelor's US institutions. Re-run the script to refresh.
insert into public.schools (scorecard_id, name, city, state, ownership, admission_rate, enrollment, domain, url)
values
${rows.join(",\n")}
on conflict (scorecard_id) do update set
  name = excluded.name, city = excluded.city, state = excluded.state,
  ownership = excluded.ownership, admission_rate = excluded.admission_rate,
  enrollment = excluded.enrollment, domain = excluded.domain, url = excluded.url;
`;
writeFileSync("supabase/migrations/0002_seed_schools.sql", sql);
console.log(`Wrote ${schools.length} schools to supabase/seed/schools.json and 0002_seed_schools.sql`);
